# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Example Function to Illustrate OpenMP Use
#'
#' This example is taken directly from the Armadillo documentation.
#' When built with OpenMP support, and running on a system with
#' multiple cores, R will likely complain about 'CPU time > 2 elapsed
#' time'. However, when environment variable 'SHOWME' is set to 'yes'
#' we throttle and no warning appears.
#'
#' @examples
#' if (Sys.getenv("SHOWME", "") == "yes")
#'    set_number_of_omp_threads(1)
#' openmp_example()
#'
openmp_example <- function() {
    invisible(.Call(`_RcppArmadilloOpenMPEx_openmp_example`))
}

#' Report Maximum Number of Threads
#'
get_number_of_omp_threads <- function() {
    .Call(`_RcppArmadilloOpenMPEx_get_number_of_omp_threads`)
}

#' Set Maximum Number of Threads
#'
#' @param n Number of threads to be set
set_number_of_omp_threads <- function(n) {
    invisible(.Call(`_RcppArmadilloOpenMPEx_set_number_of_omp_threads`, n))
}

