# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Example Function
#'
#' @examples
#' ncores <- Sys.getenv("OMP_NUM_THREADS", 2)
#' Sys.setenv("OMP_NUM_THREADS"=2)
#' example()
#' Sys.setenv("OMP_NUM_THREADS"=ncores)
#'
example <- function() {
    invisible(.Call(`_RcppArmadilloOpenMPEx_example`))
}

